ShoppingHelper/Models/TipProdus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace ShoppingHelper
{
    public class TipProdus
    {
        [Key]
        [ScaffoldColumn(false)]
        public int Id {get; set;}

        [Required, StringLength(1000), Display(Name = "Denumire Produs")]
        public string Denumire { get; set; }

        [Display(Name = "Unitate de Masura")]
        public string UnitateMasura { get; set; }

        public virtual ICollection<Produs> Produs { get; set; }



    }
}

ShoppingHelper/Controllers/ShoppingListPerStoreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShoppingHelper;
using ShoppingHelper;
using System.Data.Entity.Infrastructure;
using System.Web.Security;

namespace ShoppingHelper.Controllers
{
    [Authorize]
    public class ShoppingListPerStoreController : Controller
    {
        private ShoppingContext db = new ShoppingContext();
        private List<Produs> produseList;
        private List<TipProdus> tipProdusList;
        public List<ShoppingListPerStore> shoppingList=new List<ShoppingListPerStore>();
        private ShoppingListPerStore shop = new ShoppingListPerStore();
        private List<Magazin> magazine;

        public ViewResult NoData()
        {
            return View();
        }
        //
        // GET: /ShoppingListPerStore/

        public ViewResult Index()
        {
            tipProdusList = Session["ShoppingList"] as List<TipProdus>;

            if (tipProdusList == null)
            {
                throw new Exception("Nu este Lista de cumparaturi in Sesiune!");
            }
          //  tipProdusList = db.TipProduse.ToList();
            produseList = db.Produse.ToList();
           //s tipProdusList = db.TipProduse.Where(p => p.Id == 1).ToList();
            magazine = db.Magazine.ToList();

            foreach (var tipProdus in tipProdusList)
            {
                var produse = produseList.Where(p => p.IdTipProdus == tipProdus.Id);
                var listaMagazinePerProdus = produse.Select(p => p.Magazin).ToList();
                magazine = magazine.Intersect(listaMagazinePerProdus).ToList();
            }

            var pretMinim = decimal.MaxValue;
            Magazin magazinCuPretMinim = null;
            foreach (Magazin magazin in magazine)
            {
                shop.PretTotal = (from x in produseList
                                  where x.IdMagazin == magazin.Id
                                  select x.Pret).Sum();
                if(pretMinim>shop.PretTotal)
                {
                    pretMinim = shop.PretTotal;
                    magazinCuPretMinim  = magazin;
                }
                shop.MagazinId = magazin.Id;
                shop.Produse = produseList;
                shop.TipProdus = tipProdusList;
                shoppingList.Add(shop);
                RefreshShoppingList();
            }


            if (shoppingList.Count() == 0)
            {
                return View("NoData");
            }

            string email = Membership.GetUser().Email;
            string subject= "Comanda realizata la magazinul ales";
            string content = string.Format("Buna ziua! \r\n Ne bucuram ca puteti face o alegere cu ajutorul aplicatiei noastre de usurat viata! \r\n Ati ales produsele: \r\n");

            foreach (var product in produseList)
            {
                content += string.Format("{0} {1} {2} \r\n",product.TipProdus.Denumire , product.TipProdus.UnitateMasura, product.Pret);
            }

            content += string.Format(" de la magazinul {0}", magazinCuPretMinim.Nume);
            HomeController.GmailTeste(email, subject, content);

            return View("Index", shoppingList);
        }

        private void RefreshShoppingList()
        {
            shop = new ShoppingListPerStore();
            shop.Produse = produseList;
            shop.TipProdus = tipProdusList;
            
        }

      
    }
}

ShoppingHelper/Controllers/TipProdusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShoppingHelper;

namespace ShoppingHelper.Controllers
{
    [Authorize]
    public class TipProdusController : Controller
    {
        private ShoppingContext db = new ShoppingContext();

        //
        // GET: /TipProdus/

        public ViewResult Index()
        {
            return View(db.TipProduse.ToList());
        }

        public ViewResult Comanda()
        {
            return View(db.TipProduse.ToList());
        }

        //
        // POST: /TipProdus/Comanda/5

        [HttpPost]
        public ActionResult Comanda(string[] orderedIds)
        {
            orderedIds = ((string[])(orderedIds))[0].Replace("[", "").Replace("]", "").Replace("\\", "").Replace("\"", "").Split(',');
            List<int> ids = orderedIds
                                .Where(id => id != "")
                                .Select(id => Convert.ToInt32(id)).ToList();
            var tipProduse = db.TipProduse
                                    .Where(tp => ids.Contains(tp.Id));

            Session["ShoppingList"] = tipProduse.ToList();

            return RedirectToAction("Index");
       
       //     return RedirectToAction("Index", "ShoppingListPerStore");
        }

        public ViewResult RedirectToShoppingList()
        {
            return View();
        }

        //
        // GET: /TipProdus/Details/5

        public ViewResult Details(int id)
        {
            TipProdus tipprodus = db.TipProduse.Find(id);
            return View(tipprodus);
        }

        //
        // GET: /TipProdus/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /TipProdus/Create

        [HttpPost]
        public ActionResult Create(TipProdus tipprodus)
        {
            if (ModelState.IsValid)
            {
                db.TipProduse.Add(tipprodus);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(tipprodus);
        }
        
        //
        // GET: /TipProdus/Edit/5
 
        public ActionResult Edit(int id)
        {
            TipProdus tipprodus = db.TipProduse.Find(id);
            return View(tipprodus);
        }

        //
        // POST: /TipProdus/Edit/5

        [HttpPost]
        public ActionResult Edit(TipProdus tipprodus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipprodus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipprodus);
        }

        //
        // GET: /TipProdus/Delete/5
 
        public ActionResult Delete(int id)
        {
            TipProdus tipprodus = db.TipProduse.Find(id);
            return View(tipprodus);
        }

        //
        // POST: /TipProdus/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            TipProdus tipprodus = db.TipProduse.Find(id);
            db.TipProduse.Remove(tipprodus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ShoppingHelper/Views/TipProdus/Comanda.cshtml
@model IEnumerable<ShoppingHelper.TipProdus>
@{
    ViewBag.Title = "Comanda";
}
 <script type="text/javascript" src="../../Scripts/jquery.json-2.3.min.js"></script>
<h2>Comanda</h2>
<div>
    @Html.ActionLink("Go back", "Index")
</div>
<table class="pagination-centered table">
    <tr>
        <th></th>
        <th>Denumire
        </th>
        <th>UnitateMasura
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <input type="checkbox" name="selectedObjects" onclick= "selectedObjectsClick(this,'@Html.DisplayFor(model => item.Id)    ')"
                 value="<%: item.Id%>" />
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Denumire)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitateMasura)
            </td>
        </tr>
    }
</table>
<p>
    <a class="btn btn-primary" href='#' onclick="submitClick()">Trimite </a>
    @Html.ActionLink("Fa listele", "Index", "ShoppingListPerStore") |
</p>

<script>

    var ids = new Array();

    function selectedObjectsClick(obj,itemId) {
        if (obj.checked) {
            ids.push(itemId);
        }
        else {
            ids.pop(itemId);
        }
    }

    function submitClick() {
        var postData = $.toJSON(ids);
        var url = '@Url.Action("Comanda", "TipProdus")';
        $.post
        $.ajax(
        {
            type: "POST",
            async: false,
            url: url,
            dataType: "html",
            data: { orderedIds: postData },
            success: function (result) {
                if (result.redirect) {
                    window.location.href = result.redirect;
                    return;
                }
            },
            error: function (req, status, error) {
                alert(error);
            }
        });
    }
</script>

ShoppingHelper/Views/TipProdus/Create.cshtml
@model ShoppingHelper.TipProdus
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    <div class="text-error">
        @Html.ValidationSummary(true)
    </div>
    <fieldset>
        <legend>TipProdus</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Denumire)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Denumire)
            <div class="text-error">
                @Html.ValidationMessageFor(model => model.Denumire)
            </div>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UnitateMasura)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UnitateMasura)
            <div class="text-error">
                @Html.ValidationMessageFor(model => model.UnitateMasura)
            </div>
        </div>

        <p>
            <input class="btn btn-primary" type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShoppingHelper/Views/TipProdus/Delete.cshtml
@model ShoppingHelper.TipProdus
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
@Html.ActionLink("Back to List", "Index")
<table class="pagination-centered table">

    <tr>

        <th>Tip Produs
        </th>
        <th>Denumire
        </th>
        <th>UnitateMasura</th>
    </tr>
    <tr>
        <td></td>
        <td>
            @Html.DisplayFor(model => model.Denumire)
        </td>
        <td>
            @Html.DisplayFor(model => model.UnitateMasura)
        </td>
    </tr>
</table>

@using (Html.BeginForm())
{
    <p>
        <input class="btn btn-primary" type="submit" value="Delete" />
    </p>
}

ShoppingHelper/Views/TipProdus/Details.cshtml
@model ShoppingHelper.TipProdus
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
@Html.ActionLink("Back to List", "Index")
<table class="pagination-centered table">

    <tr>
        <th>Tip Produs
        </th>
        <th>Unitate Masura
        </th>
        <th></th>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(model => model.Denumire)
        </td>
        <td>
            @Html.DisplayFor(model => model.UnitateMasura)
        </td>
    </tr>
</table>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
</p>

ShoppingHelper/Views/TipProdus/Edit.cshtml
@model ShoppingHelper.TipProdus
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@using (Html.BeginForm())
{ <div class="pagination-centered text-error">
    @Html.ValidationSummary(true)
    </div>
    <fieldset>
        <legend>TipProdus</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Denumire)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Denumire)
            <div class="text-error">
                @Html.ValidationMessageFor(model => model.Denumire)
            </div>
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UnitateMasura)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UnitateMasura)
            <div class="text-error">
                @Html.ValidationMessageFor(model => model.UnitateMasura)
            </div>
        </div>

        <p>
            <input class="btn btn-primary" type="submit" value="Save" />
        </p>
    </fieldset>
}

ShoppingHelper/Views/TipProdus/Index.cshtml
@model IEnumerable<ShoppingHelper.TipProdus>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="pagination-centered table">
    <tr>
        <th>
            Denumire
        </th>
        <th>
            UnitateMasura
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Denumire)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitateMasura)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ShoppingHelper/Views/TipProdus/RedirectToShoppingList.cshtml
@{
    ViewBag.Title = "RedirectToShoppingList";
}

<h2>RedirectToShoppingList</h2>